# Uncomment the next line to define a global platform for your project
platform :osx, '10.15'

target 'ObjectMapperEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end

target 'XcodePlgin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end
